version: '3'
services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      image: prueba:latest
      container_name: prueba
      ports:
          - '8000:80'
      restart: always
      volumes:
          - 'html_volumen_v1:/var/www/html/storage/app'
      networks:
          - coneccion_v1
      depends_on:
          - postgres
  postgres:
      image: 'postgres:12.9'
      container_name: postgres
      restart: always
      ports:
          - '5431:5432'
      environment:
          POSTGRES_DB: '${DB_DATABASE}'
          POSTGRES_USER: '${DB_USERNAME}'
          POSTGRES_PASSWORD: '${DB_PASSWORD}'
          POSTGRES_HOST_AUTH_METHOD: 'md5'
      volumes:
          - 'db_volumen_v1:/var/lib/postgresql/data'
      networks:
          - coneccion_v1
networks:
    coneccion_v1:
        driver: bridge

volumes:
  db_volumen_v1:
  html_volumen_v1: